image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Probar Conexión SSH
        script:
          - pipe: atlassian/ssh-run:0.4.3
            variables:
              SSH_USER: "$SSH_USER"  
              SERVER: "$SSH_HOST"
              SSH_KEY: "$SSH_KEY"
              COMMAND: |
                echo "Conexión SSH exitosa!"
                hostname
