pipelines:
  branches:
    main:
      - step:
          name: Build & Push Docker Image
          runs-on:
            - self.hosted
            - linux
          services: [ docker ]
          script:
            - echo "Building image…"
            - docker build -t pepewee/whatsapp-api-cloud:$VERSION .
            - docker tag pepewee/whatsapp-api-cloud:$VERSION pepewee/whatsapp-api-cloud:latest
            - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
            - docker push pepewee/whatsapp-api-cloud:$VERSION
            - docker push pepewee/whatsapp-api-cloud:latest

      - step:
          name: Deploy to Server
          runs-on:
            - self.hosted
            - linux
          script:
            - pipe: atlassian/ssh-run:0.8.1
              variables:
                SSH_USER: "$SSH_USER"
                SERVER:   "$SSH_HOST"
                SSH_KEY:  "$SSH_KEY"
                COMMAND: >
                  docker rm -f whatsapp-api-cloud-db whatsapp-api-cloud-app || true &&
                  cd /data/sites/ia-sp-backoffice.ucatolica.cue.ec/html/back-end &&
                  echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin &&
                  docker pull pepewee/whatsapp-api-cloud:latest &&
                  docker-compose down --remove-orphans &&
                  docker-compose up -d --force-recreate --remove-orphans
