services:
  backend:
    container_name: whatsapp-api-cloud-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    volumes:
      - .:/app
      - whatsappapicloud_logs:/backend/var/log
      - ./welcome_message.txt:/app/doc/welcome_message.txt
    networks:
      - virtual_assistant_network
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  db:
    container_name: whatsapp-api-cloud-db
    image: postgres:13.3
    ports:
      - "5433:5432"
    networks:
      - virtual_assistant_network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s

  redis:
    container_name: whatsapp-api-cloud-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - virtual_assistant_network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  whatsappapicloud_logs:
  redis_data:

networks:
  virtual_assistant_network:
    external: true
