# Etapa de desarrollo
FROM maven:3.9.11-eclipse-temurin-21-noble

WORKDIR /app

# Copia el pom para cachear dependencias
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia el código fuente
COPY src ./src

# Instala DevTools
RUN mvn dependency:resolve -Dincludes=org.springframework.boot:spring-boot-devtools

# Expone el puerto
EXPOSE 8082

# Ejecuta en modo desarrollo (no empaca el jar)
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=docker"]
