version: '3.9'

services:
  backend:
    container_name: whatsapp-api-cloud-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # restart: always
    volumes:
      - .:/app
      - whatsappapicould_logs_dev:/backend/var/log
    networks:
      - virtual_assistant_network

  db:
    container_name: whatsapp-api-cloud-db
    image: postgres:13.3
    ports:
      - "5433:5432"
    networks:
      - virtual_assistant_network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  whatsappapicould_logs_dev:

networks:
  virtual_assistant_network:
    external: true
